Class {
	#name : #Null,
	#superclass : #Effect,
	#category : #'IngSoft2-Model'
}

{ #category : #'instance creation' }
Null class >> create [

	^ self new initialize.
]

{ #category : #playing }
Null >> initialize [
	
]

{ #category : #playing }
Null >> triggerReversePolarityEffectBy:aSpaceship on: anEffectManager [

	
]

{ #category : #playing }
Null >> triggeredBy: aSpaceship on: anEffectManager [

	
]
